"""primary key is id

Revision ID: 9720ec0dedab
Revises: 01dd8f54d65f
Create Date: 2020-11-09 05:19:14.789948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9720ec0dedab"
down_revision = "01dd8f54d65f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Shows", "artist_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("Shows", "venue_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Shows", "venue_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("Shows", "artist_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
