"""Implement Show and Artist models

Revision ID: c31c65bc2f67
Revises: 1e88dbb08976
Create Date: 2020-10-31 15:24:21.321403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c31c65bc2f67"
down_revision = "1e88dbb08976"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Show",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "venue_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Show")
    # ### end Alembic commands ###
