"""models schema update

Revision ID: d6a021481263
Revises: a7742f611f01
Create Date: 2020-11-13 20:03:14.038988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6a021481263"
down_revision = "a7742f611f01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Show", sa.Column("artist_image_link", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Show", sa.Column("artist_name", sa.String(length=120), nullable=True)
    )
    op.add_column("Show", sa.Column("venue_name", sa.String(length=120), nullable=True))
    op.add_column("Venue", sa.Column("genres", sa.String(length=120), nullable=True))
    op.add_column(
        "Venue", sa.Column("seeking_description", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Venue", sa.Column("seeking_talent", sa.String(length=120), nullable=True)
    )
    op.add_column("Venue", sa.Column("website", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Venue", "website")
    op.drop_column("Venue", "seeking_talent")
    op.drop_column("Venue", "seeking_description")
    op.drop_column("Venue", "genres")
    op.drop_column("Show", "venue_name")
    op.drop_column("Show", "artist_name")
    op.drop_column("Show", "artist_image_link")
    # ### end Alembic commands ###
